import uuid
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, declared_attr
from .db_util import generate_correct_spelling_table_name


class Base(DeclarativeBase):
    """
    Abstract base class for all SQLAlchemy models.

    This class serves as the foundation for all database models, providing a common
    structure including a universally unique `id` field and an automatically generated
    table name based on the class name. It inherits from SQLAlchemy's DeclarativeBase
    and is marked as abstract, meaning it won't be mapped to a database table itself.

    Attributes:
        id (Mapped[uuid.UUID]): A universally unique identifier for the model instance.
            - Uses UUID4 for default generation.
            - Serves as the primary key, is indexed, unique, and non-nullable.

    Class Behavior:
        __tablename__: Automatically generates a correct, consistent table name
            using the lowercase class name via a declared attribute. This ensures
            standardized naming across all derived models.

    Example:
        >>> class User(Base):
        ...     __tablename__ = 'users'  # Automatically set
        ...     name = mapped_column(String)

    Note:
        The __tablename__ is generated by the `generate_correct_spelling_table_name`
        function, which may apply additional formatting rules for consistency.
    """

    __abstract__ = True
    id: Mapped[uuid.UUID] = mapped_column(
        type_=UUID(as_uuid=True),
        unique=True,
        nullable=False,
        primary_key=True,
        index=True,
        default=uuid.uuid4,
    )

    @declared_attr.directive
    def __tablename__(cls):
        return generate_correct_spelling_table_name(
            name=cls.__name__.lower(),
        )
