class DataBaseException(Exception): ...


class ObjectNotFoundError(DataBaseException): ...


class ObjectAlreadyExistsError(DataBaseException): ...


class EmptyUpdateError(DataBaseException): ...


class UnsafeDeleteError(DataBaseException): ...
